### ISSUE TITLE
Vuex types are not working with Typescript 2.8.3 for a root store with modules and state key-value pairs

### ISSUE THREAD

**Issue by ChristianStornowski** [vuejs/vuex#1255]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex](https://github.com/vuejs/vuex)

### Steps to reproduce
1. clone https://github.com/vuejs/vuex
2. change to typescript 2.8.3
3. npm run test:types

### What is expected?
No type error or warning was printed in console

### What is actually happening?
error TS2345: Argument of type '{ state: { value: number; }; modules: { a: { modules: { b: { state: { value: number; }; }; }; }; ...' is not assignable to parameter of type 'StoreOptions<RootState>'.
  Types of property 'state' are incompatible.
    Type '{ value: number; }' is not assignable to type 'RootState | undefined'.
      Type '{ value: number; }' is not assignable to type 'RootState'.
        Property 'a' is missing in type '{ value: number; }'.

**Comment by ktsn** [comment]
Cannot reproduce. Is it really happened on your environment? Which line / file produce it?

**Comment by ChristianStornowski** [comment]
Sorry for the missing information.

You have to remove the namespace lines from file types/test/index.ts. Because in my situation I want to create a new Store with submodules and a value for my root store.

```
interface RootState {
    value: number;
    a: {
        value: number;
    };
};

const module = {
    state: {
        value: 0
    }
};

const store = new Vuex.Store<RootState>({
    state: {
        value: 0
    },
    modules: {
        a: module
    }
});
```

**Comment by ktsn** [comment]
> You have to remove the namespace lines from file types/test/index.ts.

Well, then this is not a problem of Vuex type itself... If you want to ask some usage question, please use [our forum](https://forum.vuejs.org/), [chat room](https://chat.vuejs.org/) or StackOverflow since issue tracker of this repo is only for feature request and bug reports.

**Comment by ChristianStornowski** [comment]
I created an example of my problem in test.ts:

https://codesandbox.io/s/14njpn10p3

1. npm run test:types

**Comment by Jason-Terry** [comment]
@ChristianStornowski did you ever find a solution to this?

**Comment by ChristianStornowski** [comment]
I didn't found a solution but I think vuex 4 solved this problem. I didn't tested vuex 4 yet.
