### ISSUE TITLE
Blank page after vuex upgrade to 3.6.1

### ISSUE THREAD

**Issue by Daniel4Digital** [vuejs/vuex#1929]
### Version
3.6.1

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue) (Sorry I dont know how to recreate the issue here, and don't have time, at the moment, to figure out how that works)

### Steps to reproduce
I am using vuex, without vue-router just so you know, and after updating 3.6.0 to 3.6.1 the page becomes blank, and the console has an error:

```
vuex.esm-bundler.js?16b2:589 Uncaught TypeError: (0 , vue__WEBPACK_IMPORTED_MODULE_0__.reactive) is not a function
    at resetStoreState (vuex.esm-bundler.js?16b2:589)
    at new Store (vuex.esm-bundler.js?16b2:332)
    at eval (index.js?4129:122)
    at Module../resources/assets/js/store/index.js (app.js:1200)
    at __webpack_require__ (manifest.js:30)
    at eval (app.js:19)
    at Module../resources/assets/js/app.js (app.js:914)
    at __webpack_require__ (manifest.js:30)
    at checkDeferredModulesImpl (manifest.js:187)
    at webpackJsonpCallback (manifest.js:169)
```

Do I really need to create an resetState from now on?

### What is expected?
Since it is a minor version I wasn't expecting my page to crash

### What is actually happening?
The pages crashes with the error mentioned.

---
I don't have any way to have a code sandbox for this... would not be easy to recreate. But the error itself should be explanatory

**Comment by kiaking** [comment]
Oh no this is wrong. Let me check and fix. Probably would make a new release.

**Comment by craigrileyuk** [comment]
Can confirm:

    WARNING in ./node_modules/vuex/dist/vuex.esm-bundler.js 13:9-15
        export 'inject' (imported as 'inject') was not found in 'vue' (possible exports: default)
    WARNING in ./node_modules/vuex/dist/vuex.esm-bundler.js 475:9-14
        export 'watch' (imported as 'watch') was not found in 'vue' (possible exports: default)
    WARNING in ./node_modules/vuex/dist/vuex.esm-bundler.js 584:32-40
        export 'computed' (imported as 'computed') was not found in 'vue' (possible exports: default)
    WARNING in ./node_modules/vuex/dist/vuex.esm-bundler.js 589:17-25
        export 'reactive' (imported as 'reactive') was not found in 'vue' (possible exports: default)
    WARNING in ./node_modules/vuex/dist/vuex.esm-bundler.js 794:2-7
        export 'watch' (imported as 'watch') was not found in 'vue' (possible exports: default)

Looks like you've let some code from the Vue3 version leak into the bundler.

**Comment by cuebit** [comment]
@kiaking I think the module should point to vuex.esm.js not the bundler

**Comment by kiaking** [comment]
Yep!

**Comment by cuebit** [comment]
Oh looks like you already [commit the change](https://github.com/vuejs/vuex/commit/679313bf5e4de066f340a06ef9bfe08d1536fadd) 😅

**Comment by kiaking** [comment]
Done! Please upgrade to Vuex 3.6.2 🙇  Sorry for the mess! And thank you for catching it 🤝
