### ISSUE TITLE
vuex.js:451 Uncaught TypeError: handler is not a function

### ISSUE THREAD

**Issue by Leonard1980** [vuejs/vuex#369]
I have a  project that work perfectly with Vue 1.0. I tried migration to Vue 2.0 (and the corresponding Vuex, Vue router an Vue resource), and after a lot of headake I managed to adapt my code to the new version of Vue to a certain point. Now I'm stuck to this error, but I don't know what seams to be the problem:

vuex.js:451 Uncaught TypeError: handler is not a function

wrappedActionHandler @ vuex.js:451
dispatch @ vuex.js:247
boundDispatch @ vuex.js:177
mappedAction @ vuex.js:124
boundFn @ vue.js:131
click @ editMeniu.html:7 -- here is an onclick event from a button that calls the vuex action
(anonymous function) @ vue.js:1608

I would like that someone to point me to a direction like why this error could occur. Thanks.

**Comment by ktsn** [comment]
We cannot help you without the actual code that produce your problem.
And please use [the gitter](gitter.im/vuejs/vue) or [the forum](http://forum.vuejs.org/) to ask usage / support question.
The issue lists of Vue.js related projects are reserved for bug reports or feature requests exclusively.
Thanks.

**Comment by Leonard1980** [comment]
Ok, maybe I'll try the forum.
